### ISSUE TITLE
parseBAM function

### ISSUE THREAD

**Issue by sebriq** [Transipedia/dekupl-annotation#18]
I saw that the bash code getContigAnnotation use a particular function on the bam obtained after the gsnap : parseBAM. However I respect the required dependencies and I don't find any sign of this function on my server or with google.
Can you give me some informations about th origin of this function?

Thanks in advance.

**Comment by SaltyStudent** [comment]
Nevermind, I found it in getAnnotationFunctions.sh. Sorry for the inconvenience.
