### ISSUE TITLE
Bug on getContigsPerLoci.R

### ISSUE THREAD

**Issue by ZheFrenchKitchen** [Transipedia/dekupl-annotation#8]
After the downloading of dekupl-annotation, I fell into the rights issues problem :/
I don't want to reproduce all the whole process..So I'm trying to run only the last part getContigsPerLoci.R to generate ContigsPerLoci.tsv.

I did as follows : 

`Rscript /pathTor/getContigsPerLoci.R /outPutDir/ DiffContigsInfos.tsv 24
`

I get  the following errors : 

```
Error in if (as.character(mappedContigs[line, EnsemblGeneCol]) != "none") { : 
  missing value where TRUE/FALSE needed
Calls: clusterContigs
Execution halted
```
What am I missing ?

DiffContigsInfos.tsv content seems to be ok so ... Thanks

`ID	LineInSam	is_mapped	aligner	chromosome	start	end	junctions	nb_junction	exon_coord_list	other_split	strand	nb_hit	nb_mismatch	nb_deletion	nb_insertion	SNV	clipped_5p	clipped_3p	as_gene	HUGO_ID_as_gene	gene	HUGO_ID_gene	gene_5p	gene_5p_dist	gene_3p	gene_3p_dist	UTR	exonic	intronic	gene_is_diff	nb_merged_kmers	contig
	pvalue	meanA	meanB	log2FC	T1_REP1_2017	T1_REP2_2017	T1_REP3_2017	T5_REP1_2017	T5_REP2_2017	T5_REP3_2017	unT5_REP1_2017	unT5_REP2_2017	unT5_REP3_2017
AAAAAAAAAAAAAAAAAAAAAAAAAAAACGA	4811819	F	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	1	AAAAAAAAAAAAAAAAAAAAAAAAAAAACGA	0.810939	238.310272	165.812438	-0.523289	215.01	287.84	209.08	183.14	209.73
	195.06	154.27	150.61	189.56
AAAAAAAAAAAAAAAAAAAAAAAAAAAACGT	4811820	F	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	1	AAAAAAAAAAAAAAAAAAAAAAAAAAAACGT	0.810939	70.137965	57.084183	-0.297105	66.77	75.19	65.46	71.27	73.6976.33	50.07	61.61	56.57
AAAAAAAAAAAAAAAAAAAAAAAAAAAAGCG	4811821	F	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	1	AAAAAAAAAAAAAAAAAAAAAAAAAAAAGCG	0.724908	373.347986	254.496837	-0.552873	349.67	421.51	345.87	223.75	312.58
	277.75	235.46	266.99	258.04`

**Comment by mgabriel01** [comment]
Hi ZheFrenchKitchen, 

These lines belong to unmapped contigs (is_mapped==F) ; do you have lines with mapped contigs (is_mapped==T) ? 
Is it possible to attach the files DiffContigsInfos.tsv & diff_contigs.bed ?

Thanks,

Marc G.

**Comment by ZheFrenchKitchen** [comment]
diff_contigs.bed is 1 Gb...hard to attach. I can put the files in an ftp.
`grep -P "\tT\t" DiffContigsInfos.tsv 
`
It gives me nothing...does that mean any contigs map ? Hummm that's is very disturbing ? no ?

If you want Send me an email on jpvillemin--At--gmail.com, I write you back with ftp adress, username & password.

**Comment by mgabriel01** [comment]
The BED file contains only mapped contigs : probably something went wrong with the annotation step (surely related to the last update), this is why the R function cannot find them.

Ok, I'll send you a mail for the ftp adress, thanks !

Marc G.

**Comment by jaudoux** [comment]
@mgabriel01 has solved this issue with commit https://github.com/Transipedia/dekupl-annotation/commit/0f790c53f2e5e34f2e2fef2c7c2fbc12697e64c1
